sonar.projectName=s3-app-backend
sonar.projectKey=Ranuldeepanayake_s3-app-backend
#sonar.projectVersion=1.0
sonar.organization=ranuldeepanayake

#File inclusion/exclusion.
#Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
#sonar.inclusions=src/lib/**,src/messages/**,src/scripts/**,src/types/**,src/utils/**
#sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,**/*.spec.*,**/*.test.*,src/app/*,src/components/*,deployment/*,docs/*,prisma/*,scripts/*,src/**
#Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

#Test parameters.
#Test directory.
sonar.tests=test
#Test inclusions.
#sonar.test.inclusions=**/*.test.js
#Coverage report path.
sonar.javascript.lcov.reportPaths=coverage/lcov.info