name: List image tags

on:
  workflow_dispatch:
    inputs:
      #Input to select the action.
      INPUT_TAG_TYPE:
        description: 'Select tag type'
        required: true
        default: develop
        type: choice
        options:
          - DEVELOP
          - RELEASE
          - FEATURE

#Global environment variables.
env:
  INPUT_TAG_TYPE: ${{ github.event.inputs.INPUT_TAG_TYPE }}
  AWS_REGION: us-east-1
  ECR_REPOSITORY_URL: public.ecr.aws/l4a5c1v5
  ECR_REPOSITORY_GROUP: qba
  ECR_REPOSITORY_NAME: qba-back-end

#Permissions.
permissions:
  contents: read

jobs:
  list-ecr-tags:
    #Runner label.
    runs-on: self-hosted

    steps:
      #Log in to the artifact repository.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #List image tags with the AWS CLI.
      - name: List image tags
        run: |
          # aws ecr-public describe-images \
          #   --repository-name "${ECR_REPOSITORY_GROUP}/${ECR_REPOSITORY_NAME}" \
          #   --query "imageDetails[?imageTags!=null].imageTags[] | [?contains(@, '${INPUT_TAG_TYPE}')] | sort(@) | reverse(@)" \
          #   --output table

          aws ecr-public describe-images --repository-name "${ECR_REPOSITORY_GROUP}/${ECR_REPOSITORY_NAME}" \
          --query "imageDetails[?imageTags!=null].imageTags[]" --output text | \
          grep "$INPUT_TAG_TYPE" | \

          # Extract version and timestamp
          awk -F'-' '{
              version=$1;
              timestamp=$5;
              printf "%s %s %s\n", version, timestamp, $0
          }' | \

          # Sort: version descending, then timestamp descending
          sort -r -k1,1V -k2,2r | \

          # Extract full tag
          awk '{print $3}'

#Show all.
#--query 'imageDetails[].imageTags[]'

#Filter by name.
#--query 'imageDetails[].imageTags[?starts_with(@, `v`)][]'

#Filter by push time (newest).
#--query 'imageDetails | sort_by(@,& imagePushedAt) | reverse(@)[].imageTags[]' 

#List with pushed timestamp
#--query 'imageDetails[].{Tags:imageTags,PushedAt:imagePushedAt}'

#--query "imageDetails[?imageTags!=null].imageTags[] | [?contains(@, '${INPUT_TAG_TYPE}')] | sort(@) | reverse(@)" \