#Retag an image. Use this to tag an existing image with a new tag. This is useful for promoting an image to production without rebuilding it.

name: Tag for production

on:
  workflow_dispatch:
    inputs:
      #Source image tag.
      INPUT_IMAGE_TAG:
        description: "Source image tag (e.g. 1.0.0-rc.8-RELEASE*)"
        required: true

#Global environment variables.
env:
  INPUT_IMAGE_TAG: ${{ github.event.inputs.INPUT_IMAGE_TAG }}
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY_URL: 104322896078.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPOSITORY_GROUP: s3-app
  ECR_REPOSITORY_NAME: backend

#Permissions.
permissions:
  contents: read

jobs:
  list-image-tags:
    #Runner label.
    runs-on: ubuntu-latest

    
    steps:
        #Validate the input image tag (ex- 1.0.0-rc.8-RELEASE*). Only certain formats are allowed to avoid accidental tagging of wrong images.
      - name: Validate input image tag
        run: |
          #Additional safegaurd to make sure only release branches are built. This is a double check since the version number is already checked to be in the correct format.
          if [[ "${INPUT_IMAGE_TAG}" != *-rc.*-RELEASE* ]]; then
          echo "❌ invalid input image tag: ${INPUT_IMAGE_TAG}"
            exit 1          
          fi

        #Log in to the artifact repository.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

        #Verify that the AWS CLI is configured correctly.
      - name: Verify AWS CLI
        run: |
          aws --version
          aws sts get-caller-identity

        #Verify if the input image tag exists in the ECR repository.
      - name: Verify input image tag
        run: |
          #Get manifest of existing image.
          MANIFEST=$(aws ecr batch-get-image --repository-name ${ECR_REPOSITORY_GROUP}/${ECR_REPOSITORY_NAME} \
                    --image-ids imageTag=${INPUT_IMAGE_TAG} --query 'images[].imageManifest' --output text)
          echo "MANIFEST=$MANIFEST" >> $GITHUB_ENV
          echo "Manifest data: ${MANIFEST}"

        #Extract the version number from the input image tag to be used as the target image tag.
      - name: Prepare target image tag
        run: |          
          VERSION_NUMBER=$(echo ${INPUT_IMAGE_TAG} | awk -F '-' '{print $1}' | tr -d '\n')
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
          echo "Extracted version number as the target tag: ${VERSION_NUMBER}"

        #Perform the retag.
      - name: Retag image
        run: |
          aws ecr put-image --repository-name ${ECR_REPOSITORY_GROUP}/${ECR_REPOSITORY_NAME} \
          --image-tag ${VERSION_NUMBER} --image-manifest "${MANIFEST}"